import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import path from "path";
import { fileURLToPath } from "url";
import fs from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Path alias plugin for esbuild
const aliasPlugin = {
	name: 'alias',
	setup(build) {
		build.onResolve({ filter: /^@\// }, args => {
			const relativePath = args.path.slice(2); // Remove '@/'
			let resolvedPath = path.resolve(__dirname, 'src', relativePath);
			
			// Check if path exists and handle directory index files
			if (fs.existsSync(resolvedPath)) {
				const stats = fs.statSync(resolvedPath);
				if (stats.isDirectory()) {
					// Try index.ts, then index.js
					const indexTs = path.join(resolvedPath, 'index.ts');
					const indexJs = path.join(resolvedPath, 'index.js');
					if (fs.existsSync(indexTs)) {
						resolvedPath = indexTs;
					} else if (fs.existsSync(indexJs)) {
						resolvedPath = indexJs;
					}
				}
			} else {
				// Try adding .ts or .js extension
				if (fs.existsSync(resolvedPath + '.ts')) {
					resolvedPath = resolvedPath + '.ts';
				} else if (fs.existsSync(resolvedPath + '.js')) {
					resolvedPath = resolvedPath + '.js';
				}
			}
			
			return { path: resolvedPath };
		});
	}
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [aliasPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
